In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('car data.csv')
df.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [3]:
df.drop??

Signature:
df.drop(
    labels: 'IndexLabel | None' = None,
    *,
    axis: 'Axis' = 0,
    index: 'IndexLabel | None' = None,
    columns: 'IndexLabel | None' = None,
    level: 'Level | None' = None,
    inplace: 'bool' = False,
    errors: 'IgnoreRaise' = 'raise',
) -> 'DataFrame | None'
Source:   
    def drop(
        self,
        labels: IndexLabel | None = None,
        *,
        axis: Axis = 0,
        index: IndexLabel | None = None,
        columns: IndexLabel | None = None,
        level: Level | None = None,
        inplace: bool = False,
        errors: IgnoreRaise = "raise",
    ) -> DataFrame | None:
        """
        Drop specified labels from rows or columns.

        Remove rows or columns by specifying label names and corresponding
        axis, or by directly specifying index or column names. When using a
        multi-index, labels on different levels can be removed by specifying
        the level. See the :ref:`user guide <advanced.shown_levels>`
        for 

In [4]:
df.drop(columns=['Car_Name', 'Seller_Type'],inplace=True, axis=1)

In [5]:
df.head()

Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Transmission  \
0  2014           3.35           5.59       27000    Petrol       Manual   
1  2013           4.75           9.54       43000    Diesel       Manual   
2  2017           7.25           9.85        6900    Petrol       Manual   
3  2011           2.85           4.15        5200    Petrol       Manual   
4  2014           4.60           6.87       42450    Diesel       Manual   

   Owner  
0      0  
1      0  
2      0  
3      0  
4      0

In [6]:
df.isnull().sum()

Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Transmission     0
Owner            0
dtype: int64

In [7]:
df.shape

(301, 7)

In [8]:
df.describe()

Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [9]:
df = pd.get_dummies(df, columns=['Fuel_Type', 'Transmission'], drop_first=True, dtype=int)
df.head()

Year  Selling_Price  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  \
0  2014           3.35           5.59       27000      0                 0   
1  2013           4.75           9.54       43000      0                 1   
2  2017           7.25           9.85        6900      0                 0   
3  2011           2.85           4.15        5200      0                 0   
4  2014           4.60           6.87       42450      0                 1   

   Fuel_Type_Petrol  Transmission_Manual  
0                 1                    1  
1                 0                    1  
2                 1                    1  
3                 1                    1  
4                 0                    1

In [10]:
X = df.drop('Selling_Price', axis=1)
y = df['Selling_Price']

In [11]:
X.head()

Year  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  Fuel_Type_Petrol  \
0  2014           5.59       27000      0                 0                 1   
1  2013           9.54       43000      0                 1                 0   
2  2017           9.85        6900      0                 0                 1   
3  2011           4.15        5200      0                 0                 1   
4  2014           6.87       42450      0                 1                 0   

   Transmission_Manual  
0                    1  
1                    1  
2                    1  
3                    1  
4                    1

In [12]:
y.head()

0    3.35
1    4.75
2    7.25
3    2.85
4    4.60
Name: Selling_Price, dtype: float64

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.2, random_state=20)
X_train, X_test, y_train, y_test

(     Year  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  \
 293  2010          9.900       38000      0                 0   
 17   2016         10.790       43000      0                 1   
 114  2015          1.470       17000      0                 0   
 213  2011          6.790       31604      0                 0   
 161  2014          0.826       23000      0                 0   
 234  2015          5.700        4492      0                 0   
 138  2016          0.870       15000      0                 0   
 115  2015          1.470       17500      0                 0   
 78   2010         22.830       80000      0                 0   
 82   2017         25.390       15000      0                 1   
 207  2015          5.700       34797      0                 0   
 26   2013          5.870       55138      0                 0   
 265  2017          8.700       21200      0                 0   
 8    2016          8.890       20273      0                 1   
 267  2016

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [31]:
y_pred = model.predict(2014, 5.59, 27000, 0, 0, 1, 1)

TypeError: LinearModel.predict() takes 2 positional arguments but 8 were given

In [16]:
y_pred = model.predict(X_test)
y_pred

array([ 1.00562562e+01,  2.31891581e+00,  8.07650073e-01,  5.58261412e+00,
        3.30133754e+00,  9.01602852e-01,  9.13066787e+00,  2.64733491e+00,
        4.61220597e+00,  9.62520786e+00, -5.72279801e-01,  3.24333352e+00,
        2.28648032e+00,  7.14259522e+00,  6.39117993e+00,  4.16510217e+00,
        4.56205688e+00,  4.76285005e+00,  7.47753386e+00,  2.43495797e+00,
        4.43345447e-01,  1.92600221e+01,  4.53395141e+00,  2.01010690e+01,
        3.81127977e+00,  4.20135126e+00,  9.09656628e+00,  9.66006972e-01,
        2.69383048e+00, -1.29561019e+00,  1.43439054e+01,  2.29727465e+00,
        1.78866660e+00,  7.57003282e+00,  3.62257614e+00,  9.59109300e+00,
        4.34090873e+00,  7.19295187e+00,  3.31178248e+00,  7.99241530e+00,
        3.44556057e+00,  6.27158978e+00, -8.28797691e-01,  6.01852397e+00,
        2.05167145e+00,  3.55351677e+00,  6.05479260e+00,  3.05883806e+00,
        4.75835464e+00,  2.18173848e+01,  3.72442953e+00,  9.09568358e+00,
        7.62297744e+00,  

In [17]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
r2

0.7873976160428405

In [18]:
from sklearn.tree import DecisionTreeRegressor

In [19]:
dtmodel = DecisionTreeRegressor()

In [20]:
dtmodel.fit(X_train, y_train)

DecisionTreeRegressor()

In [21]:
y_pred1 = dtmodel.predict(X_test)
y_pred1

array([ 8.4 ,  3.  ,  2.85,  5.5 ,  0.6 ,  0.25,  5.  ,  2.95,  5.5 ,
        5.  ,  0.2 ,  1.15,  0.2 ,  6.  ,  5.5 ,  4.  ,  5.3 ,  4.4 ,
        6.45,  1.15,  0.45, 23.  ,  5.  , 14.5 ,  3.95,  3.9 ,  8.4 ,
        0.25,  1.15,  2.85, 14.5 ,  0.2 ,  1.15,  4.5 ,  2.85,  8.4 ,
        3.9 ,  5.5 ,  1.15,  7.75,  0.2 ,  6.15,  0.6 ,  3.9 ,  0.6 ,
        1.15,  5.5 ,  5.25,  4.4 , 23.  ,  1.15,  7.5 ,  7.75,  8.25,
        4.4 ,  4.4 ,  0.2 ,  4.15,  5.5 ,  5.5 ,  6.  ,  8.25,  8.4 ,
        5.5 ,  2.85,  6.45,  0.6 ,  5.25,  2.95,  5.5 ,  3.65,  5.5 ,
        0.6 ,  5.25,  8.35,  5.15,  0.2 ,  0.6 ,  5.5 ,  3.  ,  3.95,
        2.9 ,  0.25,  0.2 ,  8.4 ,  0.45,  4.  ,  4.  ,  5.25,  0.6 ,
        1.15, 14.5 ,  1.11,  3.9 ,  1.35,  4.4 ,  0.6 ,  7.75,  0.6 ,
        8.4 ,  0.2 ,  4.4 ,  4.4 ,  8.4 ,  1.15,  8.4 ,  7.5 ,  6.  ,
        0.25,  6.15,  0.6 ,  5.25,  4.5 ,  0.2 ,  5.5 ,  6.  ,  2.9 ,
        4.5 ,  0.2 ,  8.4 ,  0.2 ,  1.35,  1.15,  1.15,  8.4 ,  2.9 ,
        3.  ,  0.45,

In [22]:
r2_1 = r2_score(y_test, y_pred1)
r2_1

0.818031861924978

In [23]:
from sklearn.ensemble import RandomForestRegressor

In [24]:
rfModel = RandomForestRegressor()

In [25]:
rfModel.fit(X_train, y_train)

RandomForestRegressor()

In [26]:
y_pred2 = rfModel.predict(X_test)
y_pred2

array([ 7.961 ,  4.978 ,  2.744 ,  5.7205,  1.0176,  0.3332,  6.514 ,
        2.9885,  5.256 ,  6.6955,  0.234 ,  1.3566,  0.3511,  6.5405,
        5.8505,  4.134 ,  5.097 ,  4.573 ,  7.213 ,  1.2742,  0.473 ,
       16.967 ,  5.4905, 14.174 ,  3.969 ,  3.937 ,  7.7565,  0.2995,
        1.1277,  2.494 , 14.683 ,  0.5711,  1.081 ,  4.764 ,  3.6535,
        8.0125,  4.902 ,  7.0055,  1.2969,  7.641 ,  0.5801,  6.0205,
        0.46  ,  4.6305,  0.6107,  1.4764,  5.7885,  3.8   ,  4.573 ,
       16.9365,  1.5154,  7.783 ,  7.609 ,  7.454 ,  4.9915,  4.3545,
        0.231 ,  3.782 ,  5.5455,  4.688 ,  5.8085,  7.5175,  7.799 ,
        5.41  ,  2.943 ,  6.8515,  0.8101,  5.3165,  3.009 ,  5.6   ,
        3.823 ,  4.688 ,  0.414 ,  5.342 ,  7.743 ,  4.4665,  0.3005,
        0.7415,  5.3485,  3.325 ,  3.9595,  3.2785,  0.6041,  0.5801,
        8.0405,  0.656 ,  4.042 ,  3.8135,  5.7875,  0.5592,  1.2337,
       15.507 ,  1.0883,  4.0215,  1.3567,  4.2685,  0.5561,  7.717 ,
        1.0131,  7.8

In [27]:
r2_2 = r2_score(y_test, y_pred2)
r2_2

0.7897496353957202

In [28]:
rfModel.score(X_test, y_test)

0.7897496353957202

In [29]:
rfModel.score(X_train, y_train)

0.9336713744421752